autoclip: true
autoimport: true
cliptimeout: 45
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /home/kiri/.local/share/password-store
safecontent: true
mounts: {}
